extcap_parser.c: fix compilation with gcc 8
extcap_parser.c:291:23: error: cast between incompatible function types from ‘void (*)(extcap_arg *)’ {aka ‘void (*)(struct _extcap_arg *)’} to ‘void (*)(void *, void *)’ [-Werror=cast-function-type]

Change-Id: I7a03bdffa655ffb3a0160f205ddcb9943a52564c
Reviewed-on: https://code.wireshark.org/review/27266
Reviewed-by: Anders Broman <a.broman58@gmail.com>
(cherry picked from commit 5905fcd4dc54759ab6e7a64778ac38d4f2551a8a)
Reviewed-on: https://code.wireshark.org/review/27296
Reviewed-by: Guy Harris <guy@alum.mit.edu>