androiddump: Try to make MVS14.0 happy
I guess using glib's gssize instead of ssize_t should be enough for:

extcap/androiddump.c(736): error C2220: warning treated as error - no 'object' f
	ile generated
extcap/androiddump.c(736): warning C4477: 'fprintf' : format string '%I64i' requ
	ires an argument of type '__int64', but variadic argument 3 has type 'ssize_t'
extcap/androiddump.c(736): note: to simplify migration, consider the temporary
	use of /Wv:18 flag with the version of the compiler with which you used to
	build without warnings
extcap/androiddump.c(736): note: consider using '%i' in the format string
extcap/androiddump.c(736): note: consider using '%I32i' in the format string

Change-Id: I1030694aed61d413be1aad54531f99db45e99c9d
Reviewed-on: https://code.wireshark.org/review/9876
Petri-Dish: Anders Broman <a.broman58@gmail.com>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Anders Broman <a.broman58@gmail.com>