prefs.c: fix compilation with gcc 8
error: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Werror=cast-function-type]

Change-Id: Id9f791c78e45d2373c3c1ce57059ef1e973a2fb1
hange-Id: I25597a730efcd580a1dd327d4fc38ab940a8b4d8
Reviewed-on: https://code.wireshark.org/review/27263
Reviewed-by: Anders Broman <a.broman58@gmail.com>
(cherry picked from commit 092564a336118606e3ee4f41e27ec440aa32b88f)
Reviewed-on: https://code.wireshark.org/review/27298
Reviewed-by: Guy Harris <guy@alum.mit.edu>