ieee802154: fix compilation with gcc-4.
Error:
../epan/dissectors/packet-ieee802154.c: In function 'dissect_ieee802154_header_ie':
../epan/dissectors/packet-ieee802154.c:3788:10: error: variable 'remaining' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
     gint remaining = tvb_reported_length_remaining(tvb, offset) - IEEE802154_MIC_LENGTH(packet->security_level);
          ^

Change-Id: I6dadaa9e502f8f38bf476b690395727c836172fd
Reviewed-on: https://code.wireshark.org/review/32283
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Guy Harris <guy@alum.mit.edu>
(cherry picked from commit 349735613dc3e02340dc73a1dd5397310c4552c5)
Reviewed-on: https://code.wireshark.org/review/32329