Fix (-W)documentation error found by Clang
rawshark.c:889:11: error: parameter 'fd' not found in the function declaration
      [-Werror,-Wdocumentation]
 * @param fd [IN] A POSIX file descriptor.  Because that's _exactly_ the sort
          ^~
rawshark.c:889:11: note: did you mean 'pd'?
 * @param fd [IN] A POSIX file descriptor.  Because that's _exactly_ the sort
          ^~
          pd

svn path=/trunk/; revision=51280