Fix missing hf field array entries:  - In two cases, add missing entries to hf[];  - Other cases: 'if 0' the packages referring to     the missing entries.
See https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=4842

ERROR: NO ARRAY: packet-h248_annex_e.c:
Fixed:
  hf_h248_pkg_ct
  hf_h248_pkg_nt

Packages 'if 0'd out:
  hf_h248_pkg_dd
  hf_h248_pkg_root


svn path=/trunk/; revision=47524