dhcp: fix used-but-marked-unused warnings
dhcp.c:3087:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must be >= 10");
                                       ^
dhcp.c:3119:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must be 4");
                                       ^
dhcp.c:3131:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must be 4");
                                       ^
dhcp.c:3143:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must be 4");
                                       ^
dhcp.c:3155:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must >= 1");
                                       ^
dhcp.c:3176:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must >= 5");
                                       ^
dhcp.c:3201:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_dhcp_bad_length, "length must be 4");

Change-Id: If4e05284a4489e7cea75fee52733851533dacbc1
Reviewed-on: https://code.wireshark.org/review/33372
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>
Petri-Dish: Martin Kaiser <wireshark@kaiser.cx>
Tested-by: Petri Dish Buildbot
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>