opcua_simpletypes.c:94:12: error: static declaration of 'hf_opcua_NamespaceUri' follows non-static declaration
Change-Id: I2cae9691408c22a64144f5482cc536a5dc88ec6c
Reviewed-on: https://code.wireshark.org/review/2135
Reviewed-by: Anders Broman <a.broman58@gmail.com>
(cherry picked from commit 803d47d49ecfb37cc649911443edf6f1290fec90)
Reviewed-on: https://code.wireshark.org/review/2175