rbm: fix a bunch of used-but-marked-unused warnings
file-rbm.c:143:34: error: 'tree' was marked unused but was used
        proto_tree_add_int_format_value(tree, hf_rbm_integer, tvb, *offset, len, value, "%d", value);
                                        ^
file-rbm.c:374:23: error: 'offset' was marked unused but was used
        gint offset_start = *offset;
                             ^
file-rbm.c:375:48: error: 'tree' was marked unused but was used
        proto_tree* drb_tree = proto_tree_add_subtree(tree, tvb, *offset, 0, ett_variable, NULL, "Objects");
                                                      ^
file-rbm.c:375:54: error: 'tvb' was marked unused but was used
        proto_tree* drb_tree = proto_tree_add_subtree(tree, tvb, *offset, 0, ett_variable, NULL, "Objects");
                                                            ^
file-rbm.c:375:60: error: 'offset' was marked unused but was used
        proto_tree* drb_tree = proto_tree_add_subtree(tree, tvb, *offset, 0, ett_variable, NULL, "Objects");
                                                                  ^
file-rbm.c:376:21: error: 'tvb' was marked unused but was used
        dissect_rbm_object(tvb, pinfo, drb_tree, offset, NULL, NULL);
                           ^
file-rbm.c:376:26: error: 'pinfo' was marked unused but was used
        dissect_rbm_object(tvb, pinfo, drb_tree, offset, NULL, NULL);
                                ^
file-rbm.c:376:43: error: 'offset' was marked unused but was used
        dissect_rbm_object(tvb, pinfo, drb_tree, offset, NULL, NULL);
                                                 ^
file-rbm.c:377:21: error: 'tvb' was marked unused but was used
        dissect_rbm_object(tvb, pinfo, drb_tree, offset, NULL, NULL);
                           ^
file-rbm.c:377:26: error: 'pinfo' was marked unused but was used
        dissect_rbm_object(tvb, pinfo, drb_tree, offset, NULL, NULL);
                                ^
file-rbm.c:377:43: error: 'offset' was marked unused but was used
        dissect_rbm_object(tvb, pinfo, drb_tree, offset, NULL, NULL);
                                                 ^
file-rbm.c:378:32: error: 'offset' was marked unused but was used
        proto_item_set_len(drb_tree, *offset - offset_start);
                                      ^
file-rbm.c:526:26: error: 'pinfo' was marked unused but was used
                expert_add_info_format(pinfo, tree, &ei_rbm_version_unsupported, "Version %u.%u is not supported (only %u.%u)",

Change-Id: Id255df237c43c313720797a46c0e877f0f7550e0
Reviewed-on: https://code.wireshark.org/review/33370
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>
Petri-Dish: Martin Kaiser <wireshark@kaiser.cx>
Tested-by: Petri Dish Buildbot
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>