ssh: fix unused-parameter
Remove tvb and offset from ssh_keylog_hash_write_secret
not longer need after 54cd727edf

packet-ssh.c:1879:40: error: unused parameter ‘tvb’ [-Werror=unused-parameter]
packet-ssh.c:1879:49: error: unused parameter ‘offset’ [-Werror=unused-parameter]