rfc7468: fix a used-but-marked-unused warning
file-rfc7468.c:428:39: error: 'data' was marked unused but was used
    dissect_rfc7468(tvb, pinfo, tree, data);

Change-Id: I938f30edfc7cf952eadbd0cf79e4cc95bb971b2e
Reviewed-on: https://code.wireshark.org/review/33369
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>
Petri-Dish: Martin Kaiser <wireshark@kaiser.cx>
Tested-by: Petri Dish Buildbot
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>