Fix: packet-bitcoin.c:1735:6: error: 'hfi_msg_getheaders_version' undeclared (first use in this function)      &hfi_msg_getheaders_version,
caused by previous commit. Weird that the compiler on my system didn't catch that.

Change-Id: I73cb06553bdf3a37f7c3d61d85f425d7c92d5b99
Reviewed-on: https://code.wireshark.org/review/7888
Reviewed-by: Jörg Mayer <jmayer@loplof.de>