Fix up *some* of the coding style inconsistencies
- return type of a function definition is always on a seperate line
- reformat single line expert items into multiline format
- no space between functionname and (
- reformat some hf_ elements that looked different from most others
- space after , where appropriate
- Fix the following warnings and errors from checkhf.pl
  Unused href entry: epan/dissectors/packet-ieee80211.c: hf_ieee80211_ff_rcsi
  Unused href entry: epan/dissectors/packet-ieee80211.c: hf_ieee80211_ff_rcsi_aid
  Error: hf_ieee80211_ff_dsss_ofdm: FT_BOOLEAN with non-null 'convert' field missing TFS in epan/dissectors/packet-ieee80211.c
  Error: non-null hf_ieee80211_ff_dsss_ofdm 'convert' field missing 'VALS|VALS64|RVALS|TFS|CF_FUNC|FRAMENUM_TYPE|&' in epan/dissectors/packet-ieee80211.c ?
  Error: hf_ieee80211_operat_mode_field_channel_width is passing the address of a pointer to VALS in epan/dissectors/packet-ieee80211.c
  Error: hf_ieee80211_operat_mode_field_rxnss is passing the address of a pointer to VALS in epan/dissectors/packet-ieee80211.c

Change-Id: Ide51d1871755199721e65c0f62b3f6a62ef1159e
Reviewed-on: https://code.wireshark.org/review/16381
Reviewed-by: Jörg Mayer <jmayer@loplof.de>