macos-setup: patch libssh to avoid compiler errors.
At least with Xcode 15 beta on macOS 14 beta, some code in libssh gets
the warning

    error: a function declaration without a prototype is deprecated in
        all versions of C [-Werror,-Wstrict-prototypes]

because they define functions with an empty argument list as

    <type> func()

rather than

    <type> func(void)

Maybe C23 will finally consider

    <type> func()

as meaning "func() takes no arguments" rather than "func() is being
defined without prototypes".

(And, no, I don't know why it says that about a function *definition*
rather than a funciton *declaration*.)