CMake: Update a compiler version check
It looks like AppleClang 10 and 11 generate bogus missing braces
warnings as well. The macOS Intel builder, which has AppleClang
11.0.0.11000033 installed, is failing with

wireshark/epan/dissectors/packet-rtps.c:11403:63: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  coherent_set_entity_info coherent_set_entity_info_object = {0};
                                                              ^
                                                              {}

(cherry picked from commit dd07fb5a15a3cae4f83d29418ef515bed40f658a)