gitlab-ci: upgrade before anything else in fedora28.
Fix a bug in linking:
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libgnutls.so: undefined reference to `nettle_rsa_sec_decrypt@HOGWEED_4'

Change-Id: Icc85813bd72274e448667bab4a80037ec5bdd48d
Reviewed-on: https://code.wireshark.org/review/31519
Reviewed-by: Dario Lombardo <lomato@gmail.com>
(cherry picked from commit d3d70a5999260492bf7966d5432b4c46a6b3db14)
Reviewed-on: https://code.wireshark.org/review/31520