Fix most remaining detected cases where item with wrong type is used.
Error: proto_tree_add_string(.., hf_ansi_a_lai_mcc, ...) called at epan/dissectors/packet-ansi_a.c:3656 with type FT_UINT8
    (allowed types are {'FT_STRINGZPAD', 'FT_STRINGZ', 'FT_STRING'} )

Error: proto_tree_add_string(.., hf_ansi_a_lai_mnc, ...) called at epan/dissectors/packet-ansi_a.c:3666 with type FT_UINT8
    (allowed types are {'FT_STRINGZPAD', 'FT_STRINGZ', 'FT_STRING'} )

Error: proto_tree_add_none_format(.., hf_bthci_evt_vendor_codecs_item, ...) called at epan/dissectors/packet-bthci_evt.c:4712 with type FT_UINT32
    (allowed types are {'FT_NONE'} )

Error: proto_tree_add_string(.., hf_kademlia_tag_hash, ...) called at epan/dissectors/packet-edonkey.c:1100 with type FT_BYTES
    (allowed types are {'FT_STRINGZPAD', 'FT_STRINGZ', 'FT_STRING'} )

Error: proto_tree_add_string(.., hf_msmms_data_timing_pair, ...) called at epan/dissectors/packet-ms-mms.c:680 with type FT_NONE
    (allowed types are {'FT_STRINGZPAD', 'FT_STRINGZ', 'FT_STRING'} )

Error: proto_tree_add_float_format_value(.., hf_fp_tpc_po, ...) called at epan/dissectors/packet-umts_fp.c:2405 with type FT_UINT8
    (allowed types are {'FT_FLOAT'} )

Change-Id: I1ed0276ad9c810ca6b1b01d581c3d73ae28fb9ad
Reviewed-on: https://code.wireshark.org/review/38081
Petri-Dish: Martin Mathieson <martin.r.mathieson@googlemail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Martin Mathieson <martin.r.mathieson@googlemail.com>