Copy ovre from trunk ...
------------------------------------------------------------------------
r47494 | wmeier | 2013-02-05 10:04:22 -0500 (Tue, 05 Feb 2013) | 9 lines

Add missing hf[] entries found by checkhf.

 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_extentList_len
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_extent_state
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_numBlks
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_startOffset
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_volID

------------------------------------------------------------------------

svn path=/trunk-1.8/; revision=47498