IEEE 802.15.4: fix uninitialized variable warning
"status" is set by decrypt_ieee802154_payload, but GCC 7.3 is unaware:

    epan/dissectors/packet-ieee802154.c: In function 'ieee802154_decrypt_payload':
    epan/dissectors/packet-ieee802154.c:1912:9: error: 'status' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             switch (status) {
             ^~~~~~

Change-Id: Ia66e6a80f277470f8b242107275ea7467c37e212
Reviewed-on: https://code.wireshark.org/review/26372
Petri-Dish: Peter Wu <peter@lekensteyn.nl>
Tested-by: Petri Dish Buildbot
Reviewed-by: Anders Broman <a.broman58@gmail.com>