tds: use %lf instead of G_GINT64_MODIFIER for text.
On many platforms, G_GINT64_MODIFIER is "ll", that gives an error when used with
the float modifier:

../epan/dissectors/packet-tds.c:2270:55: error: length modifier 'll' results in undefined behavior or no effect with 'f' conversion specifier [-Werror,-Wformat]
                    proto_item_append_text(item, " (%"G_GINT64_MODIFIER"f)", tvb_get_letohieee_float(tvb, *offset));
                                                    ~~^~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/glib/2.58.1/lib/glib-2.0/include/glibconfig.h:56:28: note: expanded from macro 'G_GINT64_MODIFIER'
 #define G_GINT64_MODIFIER "ll"
                           ^
1 error generated.

The solution appears to revert back to %lf.

Fixes: v2.9.0rc0-2411-gdbe2d081ec
Change-Id: I470cc5395921abc14aedd501f27881d5c21c618f
Reviewed-on: https://code.wireshark.org/review/30487
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Dario Lombardo <lomato@gmail.com>