extcap: fix a compile error with Qt4
declare ExtcapArgument * as a metatype so it can be used by QVariant

  CXX    extcap_argument.moc.o
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qabstractitemmodel.h:45,
                 from /usr/include/qt4/QtGui/qabstractitemview.h:46,
                 from /usr/include/qt4/QtGui/qtreeview.h:45,
                 from /usr/include/qt4/QtGui/qtreewidget.h:45,
                 from /usr/include/qt4/QtGui/QTreeWidget:1,
                 from ./interface_tree.h:38,
                 from ./extcap_options_dialog.h:35,
                 from extcap_options_dialog.cpp:26:
/usr/include/qt4/QtCore/qmetatype.h: In instantiation of ‘static int QMetaTypeId2<T>::qt_metatype_id() [with T = ExtcapArgument*]’:
/usr/include/qt4/QtCore/qmetatype.h:230:44:   required from ‘int qMetaTypeId(T*) [with T = ExtcapArgument*]’
/usr/include/qt4/QtCore/qvariant.h:341:47:   required from ‘bool QVariant::canConvert() const [with T = ExtcapArgument*]’
extcap_options_dialog.cpp:378:74:   required from here /usr/include/qt4/QtCore/qmetatype.h:169:80: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<ExtcapArgument*>’
make[2]: *** [extcap_options_dialog.o] Error 1

Change-Id: Ib7d052a5cb550ab2595b8d9580d35ffeb62093da
Reviewed-on: https://code.wireshark.org/review/16799
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>
Petri-Dish: Martin Kaiser <wireshark@kaiser.cx>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Michael Mann <mmann78@netscape.net>