ProtoBuf: Remove an unused variable.
Remove protobuf_message_direction_type:

../epan/dissectors/packet-protobuf.c:125:20: error: unused variable 'protobuf_message_direction_type' [-Werror,-Wunused-const-variable]
VALUE_STRING_ARRAY(protobuf_message_direction_type);
                   ^

Have dissect_one_protobuf_field return a gboolean while we're here.

Change-Id: I5d9d2e3414b5668ca26d5c0a450225c3cdf5da56
Reviewed-on: https://code.wireshark.org/review/23887
Petri-Dish: Gerald Combs <gerald@wireshark.org>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Gerald Combs <gerald@wireshark.org>