TWAMP: fix compilation with gcc 8
error: cast between incompatible function types from ‘gint (*)(const void *)’ {aka ‘int (*)(const void *)’} to ‘gint (*)(const void *, const void *)’ {aka ‘int (*)(const void *, const void *)’} [-Werror=cast-function-type]

Change-Id: Ifbd57414ecea16b76321c2b7d3db1a5d0a11a888
Reviewed-on: https://code.wireshark.org/review/27262
Petri-Dish: Guy Harris <guy@alum.mit.edu>
Tested-by: Petri Dish Buildbot
Reviewed-by: Guy Harris <guy@alum.mit.edu>
(cherry picked from commit 42d43ada2e3ff92c609d6c3097ba03a2e20e1320)
Reviewed-on: https://code.wireshark.org/review/27277