Fix regression from upgrade FIX 5.0 (Revision 46944)
../../../epan/dissectors/packet-fix.h:1450:10: error: multi-character character constant [-Werror=multichar]
../../../epan/dissectors/packet-fix.h:1451:10: error: multi-character character constant [-Werror=multichar]
[...]

When FIX field type is MULTIPLESTRINGVALUE use string_string (not value_string)

And regenerated packet-fix.h

svn path=/trunk/; revision=46947