cmake: link against dl, fixes linking with gold
wsutil/filesystem.c uses dladdr (when available), but does not declare a
dependency on it. Adding it fixes a CMAKE_C(XX)_FLAGS=-fuse-ld=gold
build failure:

    run/libwsutil.so.0.0.0: error: undefined reference to 'dladdr'

This change is somehow not necessary for autotools, just for cmake.

Change-Id: I642a7d85f9c33541831262f930e73d1f47c58b60
Reviewed-on: https://code.wireshark.org/review/10906
Petri-Dish: Peter Wu <peter@lekensteyn.nl>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Jörg Mayer <jmayer@loplof.de>
Reviewed-by: Peter Wu <peter@lekensteyn.nl>
(cherry picked from commit e6a071db059b1b84a3570292b3f49844c8108627)
Reviewed-on: https://code.wireshark.org/review/11035