Thrift: Fix warning about unused variable.
/epan/dissectors/packet-thrift.c:1619:9: error: ‘type_pi’ may be used
uninitialized in this function [-Werror=maybe-uninitialized]