Fix (-W)documentation error found by Clang
../ui/preference_utils.h:40:11: error: parameter 'pref:' not found in the
      function declaration [-Werror,-Wdocumentation]
 * @param pref: A preference.
          ^~~~~
../ui/preference_utils.h:40:11: note: did you mean 'pref'?
 * @param pref: A preference.
          ^~~~~
          pref
../ui/preference_utils.h:41:11: error: parameter 'unused:' not found in the
      function declaration [-Werror,-Wdocumentation]
 * @param unused: unused
          ^~~~~~~
../ui/preference_utils.h:41:11: note: did you mean 'unused'?
 * @param unused: unused
          ^~~~~~~
          unused
../ui/preference_utils.h:48:11: error: parameter 'pref:' not found in the
      function declaration [-Werror,-Wdocumentation]
 * @param pref: A preference.
          ^~~~~
../ui/preference_utils.h:48:11: note: did you mean 'pref'?
 * @param pref: A preference.
          ^~~~~
          pref
../ui/preference_utils.h:49:11: error: parameter 'changed_p:' not found in the
      function declaration [-Werror,-Wdocumentation]
 * @param changed_p: A pointer to a gboolean. Set to TRUE if the prefere...
          ^~~~~~~~~~
../ui/preference_utils.h:49:11: note: did you mean 'changed_p'?
 * @param changed_p: A pointer to a gboolean. Set to TRUE if the prefere...
          ^~~~~~~~~~
          changed_p
../ui/preference_utils.h:60:11: error: parameter 'unused:' not found in the
      function declaration [-Werror,-Wdocumentation]
 * @param unused: unused
          ^~~~~~~
../ui/preference_utils.h:60:11: note: did you mean 'unused'?
 * @param unused: unused
          ^~~~~~~
          unused

svn path=/trunk/; revision=51275