synphasor: fix compilation with gcc-5/6.
They complain because of an uninitialized variable.

../epan/dissectors/packet-synphasor.c: In function ‘config_3_frame_fast’:
../epan/dissectors/packet-synphasor.c:782:7: error: ‘ai’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     ai[i].conv = 1;
       ^
../epan/dissectors/packet-synphasor.c:767:7: error: ‘pi’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     pi[i].unit = phasor_unit & 0x00000800 ? A : V;
       ^

Change-Id: I2013ca9ddff5551328d2b86decc5e52fe052b6d0
Reviewed-on: https://code.wireshark.org/review/34859
Reviewed-by: Dario Lombardo <lomato@gmail.com>
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>