pcapng module: Don't use a C++ reserved keyword for an identifier name
pcap_module.h is a public header with #ifdef __cplusplus, so it should
support C++ compilation and not use C++ reserved keywords like "new" for
identifier names. Prevent compilation errors like:

debian/libwiretap-dev/usr/include/wireshark/wiretap/pcapng_module.h:321:13: error: expected unqualified-id before ‘new’
debian/libwiretap-dev/usr/include/wireshark/wiretap/pcapng_module.h:321:13: error: expected ‘)’ before ‘new’

AI-Assisted: no