CMake: Specify C++ 17 when we're building with Falco libs
libscap and libsinsp require C++ 17, so make that our minimum version if
Stratoshark or falcodump are enabled.

Fixes

```
/usr/include/falcosecurity/libsinsp/fdinfo.h:279:36: error: ‘std::string_view’ has not been declared
  279 |         void add_filename_raw(std::string_view rawpath);
      |                                    ^~~~~~~~~~~
```

and similar errors when building with g++ 11.