dfilter: Fix parsing of single character hex character escapes
Fix parsing of C-style hex escape character constants with only
one hex digit.

Prevents errors like:

Error: '\x1' is too long to be a valid character constant.


(cherry picked from commit e05dfae55318c3b4e0f3176decdc2d06941fb729)