VoIP Call: fix Ubuntu Buildbot
Missing init of new sip_frame_num variable...

voip_calls_dlg.c: In function ‘voip_calls_get_info’:
voip_calls_dlg.c:132:3: error: enum conversion in initialization is invalid in C++ [-Werror=c++-compat]
voip_calls_dlg.c:132:3: error: (near initialization for ‘the_tapinfo_struct.fs_option’) [-Werror=c++-compat]
voip_calls_dlg.c:132:3: error: missing initializer for field ‘redraw’ of ‘voip_calls_tapinfo_t’ [-Werror=missing-field-initializers]
                           ^

Change-Id: Ib76dec02d03f66d365ef18926bc4507a6f70556d
Reviewed-on: https://code.wireshark.org/review/9792
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>