ieee80211: hide unused value_string variable
packet-ieee80211.c:2326:27: error: ‘vht_max_mpdu_in_amsdu’ defined but not used [-Werror=unused-const-variable=]
 static const value_string vht_max_mpdu_in_amsdu[] = {

Change-Id: If4cc416b7fe92dc7915e26d2d89abaa17b081c09
Reviewed-on: https://code.wireshark.org/review/24977
Reviewed-by: Martin Mathieson <martin.r.mathieson@googlemail.com>