Add missing hf[] entries found by checkhf.
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_extentList_len
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_extent_state
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_numBlks
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_startOffset
 ERROR: NO ARRAY: packet-fmp_notify.c, hf_fmp_volID


svn path=/trunk/; revision=47494