X11 generator: avoid extraneous parens in conditionals.
This is to avoid complaints from clang of the form:

wireshark/epan/dissectors/x11-extension-implementation.h:17021:18: error:
equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((f_class_id == 0)) {
             ~~~~~~~~~~~^~~~

Change-Id: I91d629ad47677b71909d7da517c4a6198c276186
Reviewed-on: https://code.wireshark.org/review/11186
Petri-Dish: Jeff Morriss <jeff.morriss.ws@gmail.com>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Gerald Combs <gerald@wireshark.org>
(cherry picked from commit 4a5977b587deeca40d9bbdd55a0ebf3f33059372)
Reviewed-on: https://code.wireshark.org/review/11188
Reviewed-by: Jeff Morriss <jeff.morriss.ws@gmail.com>