ansi-map: fix check_tfs errors
check_tfs.py brings up two errors about open coded true_false_string
variables where existing global ones could be used.

Error: epan/dissectors/asn1/ansi_map/packet-ansi_map-template.c
   ansi_map_Odd_Even_Ind_bool_val - could have used tfs_odd_even
   from tfs.c instead:  {"Odd", "Even"}

Error: epan/dissectors/asn1/ansi_map/packet-ansi_map-template.c
   ansi_map_ConfidentialityModes_bool_val - could have used tfs_on_off
   from tfs.c instead:  {"On", "Off"}

Fix these errors by using the recommended tfs.

ansi_map_Odd_Even_Ind_bool_val is already unused and commented out, it
seems that check_tfs.py can't detect this.

This will hopefully fix the pipeline failures in !12239.