dtd: fix build due to -Wtypedef-redefinition
dtd.h defines the type, so avoid redefining to avoid this warning:

    epan/dtd_preparse.l:113:3: warning: redefinition of typedef 'Dtd_PreParse_scanner_state_t' is a C11 feature [-Wtypedef-redefinition]

Change-Id: Id6dddb8fe082717b483a6eeae08dfde468c19c89
Fixes: v2.3.0rc0-2505-ge1282f2875 ("dtd: free memory on shutdown.")
Reviewed-on: https://code.wireshark.org/review/20266
Petri-Dish: Peter Wu <peter@lekensteyn.nl>
Reviewed-by: Peter Wu <peter@lekensteyn.nl>