Copy over revisions from the trunk:
------------------------------------------------------------------------
r33158 | etxrab | 2010-06-08 01:55:07 -0700 (Tue, 08 Jun 2010) | 1 line
Changed paths:
   M /trunk/epan/dissectors/packet-gtpv2.c

Fix packet-gtpv2.c:945:1: error: "/*" within comment
------------------------------------------------------------------------
r33159 | etxrab | 2010-06-08 03:37:03 -0700 (Tue, 08 Jun 2010) | 1 line
Changed paths:
   M /trunk/epan/dissectors/packet-gtpv2.c

Remove C++ style comment.
------------------------------------------------------------------------
r33174 | stig | 2010-06-09 01:52:56 -0700 (Wed, 09 Jun 2010) | 2 lines
Changed paths:
   M /trunk/epan/column-utils.c

Corrected a typo in "display seconds with hours and minutes".
------------------------------------------------------------------------
r33178 | stig | 2010-06-09 07:27:09 -0700 (Wed, 09 Jun 2010) | 3 lines
Changed paths:
   M /trunk/asn1/acse/acse.cnf
   M /trunk/epan/dissectors/packet-acse.c

Print correct RLRE reason in Info column.
Dump RLRQ/RLRE text in Info column even when having no reason code.
------------------------------------------------------------------------
r33200 | etxrab | 2010-06-09 13:24:23 -0700 (Wed, 09 Jun 2010) | 1 line
Changed paths:
   M /trunk/epan/dissectors/packet-diameter.c

Fix a copy paste error.
------------------------------------------------------------------------
r33201 | etxrab | 2010-06-09 13:25:50 -0700 (Wed, 09 Jun 2010) | 1 line
Changed paths:
   M /trunk/epan/libwireshark.def

Add dissector_table_foreach.
------------------------------------------------------------------------
r33204 | stig | 2010-06-10 03:13:34 -0700 (Thu, 10 Jun 2010) | 3 lines
Changed paths:
   M /trunk/gtk/menus.c
   M /trunk/gtk/proto_help.c

From Jim Young via bug 4862:
GLIB 2.14 necessary to compile Wireshark with Protocol help.
------------------------------------------------------------------------
r33209 | etxrab | 2010-06-11 04:49:01 -0700 (Fri, 11 Jun 2010) | 1 line
Changed paths:
   M /trunk/epan/dissectors/packet-sdp.c

Fix: Malformed packet if port is missing from path.
------------------------------------------------------------------------
r33210 | jmayer | 2010-06-11 09:11:42 -0700 (Fri, 11 Jun 2010) | 17 lines
Changed paths:
   M /trunk/README.DECT
   M /trunk/epan/dissectors/packet-dect.c

Andreas Schuler <andreas (A) schulerdev.de>
Updates to the DECT dissector:
- using proto_tree_add_none_format()/proto_tree_add_item() instead of
  proto_tree_add_uint_format() where it makes sense
- fixed display of full slot data
- added some references to documentation
- cleaned up packet length checking
- put descrambled bfield-data in a tree
- cleaned up some afield items
- use custom columns instead adding all infos to COL_INFO
- add some more infos to the columns

Me:
- Replace proto_tree_add_none_format(..., strvar) by
  proto_tree_add_none_format(..., "%s", strvar).
- Fix an unused variable warning.
------------------------------------------------------------------------


svn path=/trunk-1.4/; revision=33406