MAC LTE: fix compilation error
error: assignment discards 'const' qualifier from pointer target type [-Werror]

also add the missing definition of hf_mac_lte_bsr_size_median

Change-Id: I31e172a16b4afd59ba8cf5a9b281bbeaf15b6c56
Reviewed-on: https://code.wireshark.org/review/1492
Reviewed-by: Pascal Quantin <pascal.quantin@gmail.com>