pcap-common: fix build error with gcc5
gcc5 complains about the issue below, so add a trivial fixup.

  CC       libwiretap_la-pcap-common.lo
pcap-common.c: In function 'pcap_byteswap_nflog_pseudoheader':
pcap-common.c:1290:30: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
  if (!(nfhdr->nflog_version) == 0) {
                              ^
cc1: all warnings being treated as errors

Change-Id: I9f5b090ffd564f203cc3fb4ff302f2e4752865f0
Reviewed-on: https://code.wireshark.org/review/7336
Reviewed-by: Guy Harris <guy@alum.mit.edu>
(cherry picked from commit a6f4bdb874169b7ac6564fa5c17be95fed0aa8ef)
Reviewed-on: https://code.wireshark.org/review/7343