With the new HFI code the compiler complains about unused element - great!
/home/jmayer/work/wireshark/svn/trunk/epan/dissectors/packet-mint.c:205:26: error: ‘hfi_mint_control_0x0c_unknown4’ defined but not used [-Werror=unused-variable]
 static header_field_info hfi_mint_control_0x0c_unknown4 MINT_HF_INIT =
                          ^

svn path=/trunk/; revision=53154