packet-gtp.c: remove unneeded named structures
In uclibc, _header is already in sigcontext.h:

packet-gtp.c:2361:16: error: redefinition of 'struct _header'
 typedef struct _header {
                ^~~~~~~
In file included from /home/dawncrow/buildroot-test/scripts/instance-0/output/host/i686-buildroot-linux-uclibc/sysroot/usr/include/bits/sigcontext.h:30:0,
                 from /home/dawncrow/buildroot-test/scripts/instance-0/output/host/i686-buildroot-linux-uclibc/sysroot/usr/include/signal.h:311,
                 from /home/dawncrow/buildroot-test/scripts/instance-0/output/host/i686-buildroot-linux-uclibc/sysroot/usr/include/glib-2.0/glib/gbacktrace.h:36,
                 from /home/dawncrow/buildroot-test/scripts/instance-0/output/host/i686-buildroot-linux-uclibc/sysroot/usr/include/glib-2.0/glib.h:34,
                 from ../../epan/proto.h:28,
                 from ../../epan/packet.h:14,
                 from packet-gtp.c:43:
/home/dawncrow/buildroot-test/scripts/instance-0/output/host/i686-buildroot-linux-uclibc/sysroot/usr/include/asm/sigcontext.h:173:8: note: originally defined here
 struct _header {

To fix this issue, transform _header and other named structures (with
the exception of gtp_conv_info_t) into unnamed structures

Fixes:
 - http://autobuild.buildroot.org/results/c41d42fe3489bc63c42e7ce7a9eccb1b4ca7b9b2

Change-Id: I78116233c2a8dd7c54723b7cb558254bd5143bd2
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-on: https://code.wireshark.org/review/32335
Petri-Dish: Guy Harris <guy@alum.mit.edu>
Tested-by: Petri Dish Buildbot
Reviewed-by: Guy Harris <guy@alum.mit.edu>
(cherry picked from commit de3e82b94146e9e24e45312d2cee193b9519c979)
Reviewed-on: https://code.wireshark.org/review/32343