Qt: Build wireless_timeline.cpp with -Wshorten-64-to-32
[...]/wireshark/ui/qt/wireless_timeline.cpp:190:50: error: implicit
   conversion loses integer precision: 'unsigned long' to 'guint' (aka 'unsigned int')
   [-Werror,-Wshorten-64-to-32]
     guint half_window = (end_tsf - start_tsf)/2;
           ~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~^~

Change-Id: I675408f8a6c0809588ce89b2b98e05d7bfb10ed9
Reviewed-on: https://code.wireshark.org/review/21969
Petri-Dish: Stig Bjørlykke <stig@bjorlykke.org>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Stig Bjørlykke <stig@bjorlykke.org>
(cherry picked from commit eb15222af228a9f08ba7031ddec635f0e08300c5)
Reviewed-on: https://code.wireshark.org/review/21971