acdr: remove private gtypes.h header to fix the build
Gisle Vanem reported a build issue:

    In file included from epan/dissectors/packet-acdr.c:25:
    In file included from ./epan/dissectors/packet-acdr.h:13:
    f:/Programfiler/Gtk-Plus/Gtk3-3.6.4/include/glib-2.0\glib/gtypes.h(28,2): error: "Only <glib.h> can be included directly."

glib.h is already included elsewhere, so it can be safely dropped.

Change-Id: I943ffb58099253048dba3d46b520b2338c99443a
Reviewed-on: https://code.wireshark.org/review/36121
Petri-Dish: Peter Wu <peter@lekensteyn.nl>
Tested-by: Petri Dish Buildbot
Reviewed-by: Anders Broman <a.broman58@gmail.com>