IEEE 802.11: Failed to build after commit eef714b
When try to build on Windows 10 x64
and compiler Microsoft Visual Studio 2022 (VC++ 14.38, build 33135),
then get error
```
...\epan\dissectors\packet-ieee80211.c(11702,51): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
```