Fix for
[ 28%] Building C object epan/CMakeFiles/epan.dir/dissectors/packet-diameter_3gpp.c.o
/home/jmayer/work/wireshark/svn/trunk/epan/dissectors/packet-diameter_3gpp.c:232:90: error: 
      unused parameter 'tree' [-Werror,-Wunused-parameter]
  ...*tvb, packet_info *pinfo _U_, proto_tree *tree, void *data _U_) 
                                               ^
1 error generated.
make[2]: *** [epan/CMakeFiles/epan.dir/dissectors/packet-diameter_3gpp.c.o] Error 1


svn path=/trunk/; revision=50799