Qt: remove unused private member (found by clang).
Error:
ui/qt/wlan_statistics_dialog.cpp:462:9: error: private field 'retry_packets_'
is not used [-Werror,-Wunused-private-field]

Change-Id: I10785eab098db14a53ef8085421c0f1046c269f3
Reviewed-on: https://code.wireshark.org/review/18337
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Anders Broman <a.broman58@gmail.com>