Windows: Fix build without libpcap
wireshark\caputils\capture-wpcap.c:901:42: error: expected ';', ',' or ')' before '_U_'
 get_runtime_caplibs_version(GString *str _U_)
                                          ^~~

(cherry picked from commit 443f05bc92958fb03ab498c20f78c5a035e8bedb)