Qt: remove semicolon from profile model.
This causes an error due to -Werror,-Wc++98-compat-extra-semi.

../ui/qt/models/profile_model.h:21:42: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
Q_DECLARE_LOGGING_CATEGORY(profileLogger);
                                         ^
1 error generated.

Change-Id: I5c04f431ffc08e90efbee5763e0f7c9b10a039d2
Reviewed-on: https://code.wireshark.org/review/33893
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Anders Broman <a.broman58@gmail.com>