Fix two warnings when compiling with rpcap support on macOS.
One is an unused variable warning turning error, the other is

[ 71%] Building C object ui/CMakeFiles/ui.dir/recent.c.o
/Users/jmayer/worktmp/wireshark/git/ui/recent.c:494:23: error: implicit conversion loses integer precision:
      'glong' (aka 'long') to 'gint' (aka 'int') [-Werror,-Wshorten-64-to-32]
      rh->auth_type = auth_type;
                    ~ ^~~~~~~~~
1 error generated.

Please review.

Change-Id: If838f8fa1e8a76dc8c6cc78db495befdd527da92
Reviewed-on: https://code.wireshark.org/review/18544
Reviewed-by: Michael Mann <mmann78@netscape.net>
Petri-Dish: Michael Mann <mmann78@netscape.net>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Roland Knall <rknall@gmail.com>
(cherry picked from commit 42f0695f4d84093a1617ee1f35ee724aa4d98166)
Reviewed-on: https://code.wireshark.org/review/29077
Reviewed-by: Guy Harris <guy@alum.mit.edu>