NATS: Failed to build after commit 50c1fb9
OS: Windows 10 x64

Compiller: Microsoft Visual Studio 2022 (Visual Studio 17.8.6
MSBuild version 17.8.5+b5265ef37 for .NET Framework
17.8.5.5502)

When try to build, then get errors

...\wireshark\epan\dissectors\packet-nats.c(467,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
...\wireshark\epan\dissectors\packet-nats.c(503,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
...\wireshark\epan\dissectors\packet-nats.c(544,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
...\wireshark\epan\dissectors\packet-nats.c(581,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
...\wireshark\epan\dissectors\packet-nats.c(624,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
...\wireshark\epan\dissectors\packet-nats.c(682,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]
...\wireshark\epan\dissectors\packet-nats.c(724,39): error C2059: syntax error: '}' [...\wsbuild_win10\epan\dissectors\dissectors.vcxproj]