Silabs Debug Channel: Don't register a conflicting hf
There's no reason to register a FT_NONE with the same abbrev as
the FT_PROTOCOL and use the former instead of the latter for the
initial tree. Prevents:

 ** (tshark:16052) 20:51:25.470113 [Epan WARNING] epan/proto.c:9867 -- proto_register_field_init(): 'silabs-dch' exists multiple times with incompatible types: FT_NONE and FT_PROTOCOL

When ENABLE_CHECKHF_CONFLICT is ON.

Also fix some deprecated allocation patterns.