LWM: fix error: unknown option [-Werror=pragmas]
epan/dissectors/packet-lwm.c:468:21: error: unknown option after
‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
                     DIAG_OFF_STRINGOP_OVERFLOW()

gcc-warning "stringop-overflow=" was introduced in gcc7.1
https://hackmd.io/@VZ/gcc-warnings