allow use of deprecated gdk-pixbuf functions
gdk-pixbuf 2.31.2 marked GdkPixdata including as deprecated,
including gdk_pixbuf_new_from_inline. Wireshark builds with
deprecated functions turned off by default, in this case
GDK_PIXBUF_DISABLE_DEPRECATED. Patch to configure.ac to allow use of
deprecated function until upstream has ported the code, or a
replacement patch is available.

gdk-pixbuf change:
https://git.gnome.org/browse/gdk-pixbuf/commit/?id=48d76fb7f2d059013f5781b199245274998f05c9

Initial warning:
ui_utils.c: In function 'window_icon_realize_cb':
ui_utils.c:115:5: warning: implicit declaration of function 'gdk_pixbuf_new_from_inline' [-Wimplicit-function-declaration]
    icon = gdk_pixbuf_new_from_inline(-1, wsicon_16_pb_data, FALSE, NULL);
    ^
Causes these warnings due to the implicit declaration:
gui_utils.c:115:10: warning: assignment makes pointer from integer without a cast [enabled by default]
    icon = gdk_pixbuf_new_from_inline(-1, wsicon_16_pb_data, FALSE, NULL);
    ^
Fails the package checks in these lines:
E: wireshark 64bit-portability-issue gui_utils.c:115, 117, 119, 121, 512
E: wireshark 64bit-portability-issue main.c:1513, 1519, 1525, 1531
E: wireshark 64bit-portability-issue prefs_layout.c:346, 347, 348, 349, 350, 351
E: wireshark 64bit-portability-issue stock_icons.c:413, 425

[Cherry-picked to master-1.12 to get that version compiling cleanly
with warnings-as-errors enabled.]

Bug: 10750
Change-Id: I85092753058cd2e5cda527e4321a7d92ac38facd
Reviewed-on: https://code.wireshark.org/review/8578
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>
Petri-Dish: Alexis La Goutte <alexis.lagoutte@gmail.com>
Reviewed-by: Balint Reczey <balint@balintreczey.hu>
(cherry picked from commit 8f462b073755398205f3d67db0f4333c9c6984f9)
Reviewed-on: https://code.wireshark.org/review/11033
Reviewed-by: Jeff Morriss <jeff.morriss.ws@gmail.com>