Fix a compile error occurring on RedHat Enterprise Linux Workstation release 7.0 (Maipo).
This fixes a compile error with Qt version 4.8.5-8 as installed in RHEL 7.0:

  sequence_dialog.cpp: In member function 'void SequenceDialog::mouseMoved(QMouseEvent*)':
  sequence_dialog.cpp:306:35: error: 'escape' is not a member of 'Qt'
             QString raw_comment = Qt::escape(sai->comment);
                                   ^

Change-Id: Ibbf62123441645471d66aa329f0d63d0ee198017
Reviewed-on: https://code.wireshark.org/review/15682
Reviewed-by: Gerald Combs <gerald@wireshark.org>
Petri-Dish: Gerald Combs <gerald@wireshark.org>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
(cherry picked from commit 76ef2d2a3dff61f523cacc0ac868f5cc2b8f5a5f)
Reviewed-on: https://code.wireshark.org/review/15690
Reviewed-by: Guy Harris <guy@alum.mit.edu>