fix
packet-gtp.c: In function 'decode_gtp_imsi':
packet-gtp.c:3210:18: error: variable 'imsi_str' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[5]: *** [libdissectors_la-packet-gtp.lo] Error 1

by commenting out the unused variable

Change-Id: I498595f93423c599f902a1a0cc42b63cef2c4d7c
Reviewed-on: https://code.wireshark.org/review/3725
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>