Copy over: Revision 46125 - fix
/home/wireshark/builders/trunk/ubuntu1204x64/build/epan/dissectors/packet-bssgp.c: In function de_bssgp_son_transfer_app_id:
/home/wireshark/builders/trunk/ubuntu1204x64/build/epan/dissectors/packet-bssgp.c:3173:12: error: variable next_tvb set but not used
[-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

svn path=/trunk-1.8/; revision=46136