ui: Define plugins_add_description() unconditionally
Since commit 5dfde7ff ("Print extcap plugins with "tshark -G
plugins"."), compiling with -DENABLE_LUA=no -DENABLE_PLUGINS=no fails.
The definition of plugins_add_description() is guarded by HAVE_PLUGINS
|| HAVE_LUA, but that definition is used without such guards for extcap
right below, resulting in:

ui/qt/about_dialog.cpp:137:29: error: 'plugins_add_description' was not
declared in this scope

Fix this by removing the guards around plugins_add_description().

Change-Id: Ieaddfed923ae3782ade28b2f5004b6a34220659a
Fixes: 5dfde7ff83a35bb7186cd05ce61f4b139ab01203
Reviewed-on: https://code.wireshark.org/review/35852
Reviewed-by: Peter Wu <peter@lekensteyn.nl>
Petri-Dish: Peter Wu <peter@lekensteyn.nl>
Tested-by: Petri Dish Buildbot
Reviewed-by: Anders Broman <a.broman58@gmail.com>
(cherry picked from commit f605e9466b60c996d88ace1469ec19ecc44b46dd)
Reviewed-on: https://code.wireshark.org/review/35870