Copy over fixes from the trunk:
r13705:

 Warning fix: voip_calls_dlg.c:733: implicit declaration of function
 rtp_event_init_tap

r13706:

 Flag an unused argument as unused, to squelch compiler warnings, and
 don't flag a used argument as unused.

svn path=/releases/ethereal-0.10.10/; revision=13716