profinet: removed unused var.
Some compilers complain about it:
- clang (all)
- gcc 6
- gcc 7

../plugins/profinet/packet-dcerpc-pn-io.c:2608:27: error: unused variable 'pn_io_mau_type_extension' [-Werror,-Wunused-const-variable]
static const range_string pn_io_mau_type_extension[] = {

Change-Id: Iaffdad31c4ecd7459d07a74e3e2665058c9ff9ba
Reviewed-on: https://code.wireshark.org/review/24715
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Michael Mann <mmann78@netscape.net>