fix compile error
packet-gsm_sms.c: In function 'dis_field_dcs':
packet-gsm_sms.c:694:12: error: 'msg_class' may be used uninitialized in
this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
make[5]: *** [libdissectors_la-packet-gsm_sms.lo] Error 1

I suppose that 0xff is an invalid message class and therefore a
reasonable default value.

Change-Id: Iab3d3f50144b24bee4972063c2170d7a9f9b7c25
Reviewed-on: https://code.wireshark.org/review/5745
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>
Tested-by: Martin Kaiser <wireshark@kaiser.cx>