DOF: Widen a loop variable
Fix

    /wireshark/epan/dissectors/packet-dof.c:3554:21: error: loop variable has narrower type 'uint8_t' than iteration's upper bound 'const int' [bugprone-too-small-loop-variable,-warnings-as-errors]
     3554 |         for (i = 0; i < addr_key->addr.len; i++)
          |                     ^

(cherry picked from commit d97ab008562d5be1cca1994f9f1c8bc8dd4858aa)