ipv6: fix build with old 32-bit glib headers
glib versions before 2.31.2 expand GUINT_TO_POINTER(x) as (gpointer)x
instead of (gpointer)(guint)x, resulting in these errors:

    packet-ipv6.c:2129: error: cast to pointer from integer of different size
    packet-ipv6.c:2185: error: cast to pointer from integer of different size

Change-Id: I1b25060ed329ce05e4f1ab75e32a56feda8e3435
Reviewed-on: https://code.wireshark.org/review/17401
Reviewed-by: Michael Mann <mmann78@netscape.net>
Petri-Dish: Michael Mann <mmann78@netscape.net>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: João Valverde <j@v6e.pt>