Revert "Fix compile error by removing an unused variable: git/plugins/ethercat/packet-ethercat-datagram.c:513:32: error: unused variable       'tfs_ecat_fmmu_typeread' [-Werror,-Wunused-const-variable] static const true_false_string tfs_ecat_fmmu_typeread =      "
This reverts commit bc3bd625e16c2341e423dcbd26a670f059f63621.

Change-Id: Iaf1e6fe51c20811761d18e86dc8b2c8402a2c89a
Reviewed-on: https://code.wireshark.org/review/14609
Reviewed-by: Stig Bjørlykke <stig@bjorlykke.org>