wsutil: link with -lm.
Required because json_dumper.c uses isfinite, fixes FreeBSD builds.

Error:
/usr/lib/libpcap.so && :
/usr/local/bin/ld: run/libwsutil.so.0.0.0: undefined reference to `__isfinite'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Change-Id: I6376250fa2037eab0bb2ad63382b8f3bb3560215
Reviewed-on: https://code.wireshark.org/review/34138
Reviewed-by: Dario Lombardo <lomato@gmail.com>
Petri-Dish: Dario Lombardo <lomato@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Roland Knall <rknall@gmail.com>