X11: Fix missing brackets caught by GCC
packet-x11.c: In function ‘dissect_x11_request’:
packet-x11.c:3753:13: error: this ‘if’ clause does not guard...
 [-Werror=misleading-indentation]
              if (next_offset - *offsetp > 0)
              ^~
 packet-x11.c:3755:17: note: ...this statement, but the latter is misleadingly
 indented as if it is guarded by the ‘if’
                 *offsetp = next_offset;
                  ^
 cc1: all warnings being treated as errors
 Makefile:4388: recipe for target 'packet-x11.lo' failed
 make[6]: *** [packet-x11.lo] Error 1

Change-Id: I3605c316e7b84f7cec21ce54431f6816fccca100
Reviewed-on: https://code.wireshark.org/review/21199
Petri-Dish: Michael Mann <mmann78@netscape.net>
Reviewed-by: Jaap Keuter <jaap.keuter@xs4all.nl>
Reviewed-by: Pascal Quantin <pascal.quantin@gmail.com>