umts_fp: fix ... defined but not used [-Werror=unused-const-variable] found by gcc6
Change-Id: I5866ea2d6a08a90799882b0c4626d0ed215069a8
error: ‘fake_lchid_macd_flow’ defined but not used [-Werror=unused-const-variable]
error: ‘hsdsch_macdflow_id_mac_content_map’ defined but not used [-Werror=unused-const-variable]
error: ‘hsdsch_macdflow_id_rlc_map’ defined but not used [-Werror=unused-const-variable]
Reviewed-on: https://code.wireshark.org/review/13871
Petri-Dish: Anders Broman <a.broman58@gmail.com>
Tested-by: Petri Dish Buildbot <buildbot-no-reply@wireshark.org>
Reviewed-by: Anders Broman <a.broman58@gmail.com>