Add missing hf[] entries found by checkhf.
  ERROR: NO ARRAY: packet-9p.c, hf_9P_dm_exec_group
  ERROR: NO ARRAY: packet-9p.c, hf_9P_dm_read_group
  ERROR: NO ARRAY: packet-9p.c, hf_9P_dm_write_group


svn path=/trunk/; revision=47493