SMB2: Fix compilation on MSYS2
On normal Windows SYMLINK_FLAG_RELATIVE is defined in ntifs.h (which
we don't include by default), but in the case of MSYS2 it is defined
in winnt.h (which is included by windows.h), and so defining it in
the dissector can cause a redefinition warning especially with
hex vs. decimal issues:

wireshark/epan/dissectors/packet-smb2.c:1218:9: error: 'SYMLINK_FLAG_RELATIVE' redefined [-Werror]
 1218 | #define SYMLINK_FLAG_RELATIVE 0x00000001
      |         ^~~~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/ucrt64/include/minwindef.h:163,
                 from C:/msys64/ucrt64/include/windef.h:9,
                 from C:/msys64/ucrt64/include/windows.h:69,
                 from C:/msys64/home/johnt/wireshark/epan/dissectors/packet-smb2.c:52:
C:/msys64/ucrt64/include/winnt.h:6402:9: note: this is the location of the previous definition
 6402 | #define SYMLINK_FLAG_RELATIVE   1
      |         ^~~~~~~~~~~~~~~~~~~~~

Fixup 692a66d05d8a467a9a5eda29c09337b9362e3147

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_reparse_data_buffer

AI-Assisted: no