epan: fix build error with gcc5
gcc5 bails out with the below error.

  CC       libwireshark_la-tvbparse.lo
  CC       libwireshark_la-tvbuff_base64.lo
tvbparse.c: In function 'cond_not_char':
tvbparse.c:254:18: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
     if (! offset < tt->end_offset ) {
                  ^
cc1: all warnings being treated as errors
Makefile:1843: recipe for target 'libwireshark_la-tvbparse.lo' failed

Change-Id: I4e8654e97079da6b39be580fc766eecefb4c7ea6
Reviewed-on: https://code.wireshark.org/review/7339
Reviewed-by: Guy Harris <guy@alum.mit.edu>
(cherry picked from commit b125feae219aaa7afcd10a96a50863cdd83f5bd2)
Reviewed-on: https://code.wireshark.org/review/7342