blip: fix used-but-marked-unused warnings
blip.c:195:4: error: 'offset' was marked unused but was used
                        offset,
                        ^
blip.c:200:22: error: 'blip_tree' was marked unused but was used
        proto_tree_add_item(blip_tree, hf_blip_ack_size, tvb, offset, varint_ack_size_length, ENC_VARINT_PROTOBUF);
                            ^
blip.c:200:56: error: 'offset' was marked unused but was used
        proto_tree_add_item(blip_tree, hf_blip_ack_size, tvb, offset, varint_ack_size_length, ENC_VARINT_PROTOBUF);
                                                              ^
blip.c:202:2: error: 'offset' was marked unused but was used
        offset += varint_ack_size_length;
        ^
blip.c:284:14: error: 'pinfo' was marked unused but was used
        col_set_str(pinfo->cinfo, COL_PROTOCOL, "BLIP");
                    ^
blip.c:286:12: error: 'pinfo' was marked unused but was used
        col_clear(pinfo->cinfo,COL_INFO);
                  ^
blip.c:333:14: error: 'pinfo' was marked unused but was used
        col_add_str(pinfo->cinfo, COL_INFO, col_info);
                    ^
blip.c:337:34: error: 'pinfo' was marked unused but was used
                return handle_ack_message(tvb, pinfo, blip_tree, offset, value_frame_flags);
                                               ^
blip.c:346:45: error: 'pinfo' was marked unused but was used
        conversation = find_or_create_conversation(pinfo);
                                                   ^
blip.c:361:4: error: 'pinfo' was marked unused but was used
                        pinfo,
                        ^
blip.c:380:27: error: 'pinfo' was marked unused but was used
                tvb_to_use = decompress(pinfo, tvb, offset, tvb_reported_length_remaining(tvb, offset) - BLIP_BODY_CHECKSUM_SIZE);

Change-Id: I9de1a78942469cc16011fd1a21d93b81820bee80
Reviewed-on: https://code.wireshark.org/review/33373
Reviewed-by: Martin Kaiser <wireshark@kaiser.cx>
Petri-Dish: Martin Kaiser <wireshark@kaiser.cx>
Petri-Dish: Anders Broman <a.broman58@gmail.com>
Tested-by: Petri Dish Buildbot
Reviewed-by: Alexis La Goutte <alexis.lagoutte@gmail.com>