remove unused variable numelem
this fixes
  CC     libdissectors_la-packet-scsi-smc.lo
packet-scsi-smc.c: In function 'dissect_smc_readelementstatus':
packet-scsi-smc.c:467:11: error: variable 'numelem' set but not used
[-Werror=unused-but-set-variable]


svn path=/trunk/; revision=51168