GTP: Fix filtering of UL/DL items
The uplink and downlink bit rate items, and the maximum SDU size,
are contained in a single octet but added to the tree using
proto_tree_add_uint_format[_value] after multiplying by various factors,
so the values don't actually fit in a FT_UINT8. The fields need
to be large enough to fit the largest value added after transformation.

The filter engine won't allow filters for values outside the field
range, e.g.

$ ./run/dftest -s 'gtp.qos_max_sdu_size == 1500'
Filter:
 gtp.qos_max_sdu_size == 1500

Error: "1500" too big for this field, maximum 255.
  gtp.qos_max_sdu_size == 1500
                          ^~~~

After:

$ ./run/dftest -s 'gtp.qos_max_sdu_size == 1500'
Filter:
 gtp.qos_max_sdu_size == 1500

Syntax tree:
 0 TEST_ANY_EQ:
   1 FIELD(gtp.qos_max_sdu_size <FT_UINT16>)
   1 FVALUE(1500 <FT_UINT16>)

Instructions:
 0000 READ_TREE        gtp.qos_max_sdu_size -> R0
 0001 IF_FALSE_GOTO    3
 0002 ANY_EQ           R0 == 1500
 0003 RETURN