Fix compilation error:
packet-amqp.c:5617:5: error: "/*" within comment

Cause:

Previous comment wasn't terminated right


svn path=/trunk/; revision=36454