GTP: fix compilation with gcc 8
error: cast between incompatible function types from ‘void (*)(const void *, void *, void *)’ to ‘gboolean (*)(const void *, void *, void *)’ {aka ‘int (*)(const void *, void *, void *)’} [-Werror=cast-function-type]

Change-Id: If93eb9a4f38b622ae5dfaf9ed1e2c3d257141105
Reviewed-on: https://code.wireshark.org/review/27260
Reviewed-by: Guy Harris <guy@alum.mit.edu>
(cherry picked from commit 966c5957822a974ddd4f0558db0eccbbb7afe290)
Reviewed-on: https://code.wireshark.org/review/27275