Copy over revisions from the trunk:
------------------------------------------------------------------------
  r37872 | guy | 2011-07-02 18:40:12 -0700 (Sat, 02 Jul 2011) | 6 lines
  Changed paths:
     M /trunk/epan/dissectors/packet-mq.c
     M /trunk/epan/proto.c
     M /trunk/epan/proto.h

  Add ENC_ values for UTF-8 and EBCDIC, support them for FT_STRINGZ
  values, and use them in the MQ dissector, so EBCDIC strings are
  displayed as such.

  Fix up some other final arguments to proto_tree_add_item().
  ------------------------------------------------------------------------
  r37878 | guy | 2011-07-03 10:54:00 -0700 (Sun, 03 Jul 2011) | 2 lines
  Changed paths:
     M /trunk/epan/libwireshark.def

  Need to export EBCDIC_to_ASCII().
  ------------------------------------------------------------------------
  r37879 | darkjames | 2011-07-03 11:59:41 -0700 (Sun, 03 Jul 2011) | 4 lines
  Changed paths:
     M /trunk/epan/Makefile.am
     M /trunk/epan/Makefile.nmake
     M /trunk/epan/libwireshark.def

  Fix: tvbuff.obj : error LNK2019: unresolved external symbol _EBCDIC_to_ASCII referenced in function _tvb_get_ephemeral_string_enc

  Remove duplicated EBCDIC_to_ASCII from libwireshark.def
  ------------------------------------------------------------------------
  r37883 | darkjames | 2011-07-03 14:18:22 -0700 (Sun, 03 Jul 2011) | 2 lines
  Changed paths:
     M /trunk/epan/Makefile.am
     M /trunk/epan/Makefile.nmake

  Fix one more undefined reference to `EBCDIC_to_ASCII'
  ------------------------------------------------------------------------
  r37893 | etxrab | 2011-07-04 13:43:29 -0700 (Mon, 04 Jul 2011) | 14 lines
  Changed paths:
     M /trunk/epan/dissectors/packet-isup.c

  From Christopher Maynard:
  From doc/README.tapping:

  IF the tap is going to return private data using the last parameter to
  tap_queue_packet() and IF the protocol can appear multiple times inside the
  same packet, you will have to make sure that each instance of
  tap_queue_packet() is using its own instance of private struct variable
  so they don't overwrite each other.

  This was the case here, so I changed the static allocation of tap_rec to be
  ep_alloc'd.  I also tried to clean up the Info column a bit.  With this patch
  applied, the graph now shows the APM and ANM correctly instead of 2 ANM's.

  https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=5966
  ------------------------------------------------------------------------
  r37895 | stig | 2011-07-04 14:14:43 -0700 (Mon, 04 Jul 2011) | 1 line
  Changed paths:
     M /trunk/make-version.pl

  Fetch svn revision also when checked out with git-svn.
  ------------------------------------------------------------------------
  r37918 | etxrab | 2011-07-06 05:47:21 -0700 (Wed, 06 Jul 2011) | 4 lines
  Changed paths:
     M /trunk/epan/dissectors/packet-gsmtap.c

  From HAESSLER:
  Abis interface not correctly handled in gsmtap dissector

  https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=6097
  ------------------------------------------------------------------------


Copy over by hand:

------------------------------------------------------------------------
r37685 | guy | 2011-06-16 11:34:17 -0700 (Thu, 16 Jun 2011) | 2 lines
Changed paths:
   M /trunk/epan/proto.c
   M /trunk/epan/strutil.c
   M /trunk/epan/tvbuff.c
   M /trunk/epan/tvbuff.h

Squelch some compiler warnings.
------------------------------------------------------------------------
  r37876 | guy | 2011-07-03 10:08:25 -0700 (Sun, 03 Jul 2011) | 6 lines
  Changed paths:
     M /trunk/epan/dissectors/packet-mq.c
     M /trunk/epan/libwireshark.def
     M /trunk/epan/proto.h
     M /trunk/epan/tvbuff.c
     M /trunk/epan/tvbuff.h

  Add a tvb_get_ephemeral_string_enc() routine that's like
  tvb_get_ephemeral_string() but takes an ENC_ value for the character
  encoding.  Use it in the MQ dissector to fetch strings to put, for
  example, into the Info column, so we properly handle EBCDIC strings
  there.
  ------------------------------------------------------------------------


Update the release notes.

svn path=/trunk-1.6/; revision=38002